/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject18;



/**
 *
 * @author mildi
 */


public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        YbsHavaYolları = new javax.swing.JLabel();
        Resim = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AdıSoyadı = new javax.swing.JLabel();
        Tc = new javax.swing.JLabel();
        Tel = new javax.swing.JLabel();
        HesKodu = new javax.swing.JLabel();
        AdSoyadText = new javax.swing.JTextField();
        TcText = new javax.swing.JTextField();
        TelText = new javax.swing.JTextField();
        HesKoduText = new javax.swing.JTextField();
        YolcuBilgileri = new javax.swing.JLabel();
        Cinsiyet = new javax.swing.JLabel();
        Erkek = new javax.swing.JRadioButton();
        Kadın = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        Nereden = new javax.swing.JLabel();
        Nereye = new javax.swing.JLabel();
        Tarih = new javax.swing.JLabel();
        Saat = new javax.swing.JLabel();
        UçuşBilgileri = new javax.swing.JLabel();
        NeredenCB = new javax.swing.JComboBox<>();
        NereyeCB = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        SaatCB = new javax.swing.JComboBox<>();
        DkCB = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        YbsHavaYolları.setFont(new java.awt.Font("Ink Free", 3, 24)); // NOI18N
        YbsHavaYolları.setText("YBS HAVA YOLLARI");

        Resim.setBackground(new java.awt.Color(255, 255, 255));
        Resim.setIcon(new javax.swing.ImageIcon("C:\\Users\\mildi\\OneDrive\\Masaüstü\\indir.png")); // NOI18N
        Resim.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(YbsHavaYolları, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Resim, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(YbsHavaYolları, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Resim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        AdıSoyadı.setText("Adı Soyadı : ");

        Tc.setText("Tc:");

        Tel.setText("Tel : ");

        HesKodu.setText("Hes Kodu : ");

        AdSoyadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdSoyadTextActionPerformed(evt);
            }
        });

        TcText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TcTextMouseClicked(evt);
            }
        });
        TcText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TcTextActionPerformed(evt);
            }
        });
        TcText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TcTextKeyTyped(evt);
            }
        });

        TelText.setText("+90");

        HesKoduText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HesKoduTextActionPerformed(evt);
            }
        });

        YolcuBilgileri.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        YolcuBilgileri.setText("Yolcu Bilgileri");

        Cinsiyet.setText("Cinsiyet : ");

        buttonGroup1.add(Erkek);
        Erkek.setText("Erkek");
        Erkek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErkekActionPerformed(evt);
            }
        });

        buttonGroup1.add(Kadın);
        Kadın.setText("Kadın");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(YolcuBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cinsiyet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AdıSoyadı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HesKodu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AdSoyadText, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(TcText)
                                .addComponent(TelText)
                                .addComponent(HesKoduText))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Erkek, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Kadın, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YolcuBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdıSoyadı)
                    .addComponent(AdSoyadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tc)
                    .addComponent(TcText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tel)
                    .addComponent(TelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HesKodu)
                    .addComponent(HesKoduText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cinsiyet)
                    .addComponent(Erkek)
                    .addComponent(Kadın))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        Nereden.setText("Nereden : ");

        Nereye.setText("Nereye : ");

        Tarih.setText("Tarih : ");

        Saat.setText("Saat : ");

        UçuşBilgileri.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        UçuşBilgileri.setText("Uçuş Bilgileri");

        NeredenCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esenboğa-Ankara", "İstanbul-İstanbul", "Sabiha Gökçen-İstanbul", "Antalya-Antalya", "Adnan Menderes-İzmir", "Adana-Adana", "Dalaman-Muğla", "Milas-Bodrum-Muğla", "Trabzon-Trabzon", "Gaziantep-Gaziantep", "Kayseri-Kayseri", "Diyarbakır-Diyarbakır", "Samsun Çarşamba-Samsun", "Van Ferit Melen\t-Van", "Erzurum-Erzurum", "Hatay-Hatay", "Gazipaşa-Antalya", "Konya-Konya", "Ordu-Giresun-Ordu", "Elazığ-Elâzığ", "Malatya-Malatya", "Şanlıurfa GAP-Şanlıurfa", "Denizli Çardak-Denizli", "Sivas Nuri Demirağ-Sivas", "Kars-Kars", "Balıkesir Koca Seyit-Balıkesir\t", "Kapadokya-Nevşehir", "Bursa Yenişehir-Bursa", "Çanakkale-Çanakkale", "Sinop-Sinop", "Süleyman Demirel-Isparta", "Tekirdağ Çorlu-Tekirdağ", "Zafer-Kütahya", "Hasan Polatkan\t-Eskişehir", "Kocaeli Cengiz Topel-Kocaeli", "Zonguldak Çaycuma-Zonguldak", "Uşak-Uşak", "Mardin-Mardin", "Batman-Batman", "Erzincan-Erzincan", "Muş Sultan Alparslan-Muş", "Şırnak Şerafettin Elçi-Şırnak", "Kahramanmaraş-Kahramanmaraş", "Ağrı Ahmed-i Hani-Ağrı", "Iğdır Şehit Bülent Aydın-Iğdır", "Adıyaman-Adıyaman\t", "Bingöl-Bingöl\t", "Yüksekova Selahaddin Eyyubi-Hakkari", "Amasya Merzifon-Amasya\t", "Kastamonu-Kastamonu\t", "Siirt-Siirt", "Tokat-Tokat\t", "Aydın Çıldır-Aydın", "Balıkesir Merkez-Balıkesir", "Çanakkale Gökçeada-Çanakkale" }));

        NereyeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İstanbul-İstanbul", "Sabiha Gökçen-İstanbul", "Esenboğa-Ankara", "Antalya-Antalya", "Adnan Menderes-İzmir", "Adana-Adana", "Dalaman-Muğla", "Milas-Bodrum-Muğla", "Trabzon-Trabzon", "Gaziantep-Gaziantep", "Kayseri-Kayseri", "Diyarbakır-Diyarbakır", "Samsun Çarşamba-Samsun", "Van Ferit Melen\t-Van", "Erzurum-Erzurum", "Hatay-Hatay", "Gazipaşa-Antalya", "Konya-Konya", "Ordu-Giresun-Ordu", "Elazığ-Elâzığ", "Malatya-Malatya", "Şanlıurfa GAP-Şanlıurfa", "Denizli Çardak-Denizli", "Sivas Nuri Demirağ-Sivas", "Kars-Kars", "Balıkesir Koca Seyit-Balıkesir\t", "Kapadokya-Nevşehir", "Bursa Yenişehir-Bursa", "Çanakkale-Çanakkale", "Sinop-Sinop", "Süleyman Demirel-Isparta", "Tekirdağ Çorlu-Tekirdağ", "Zafer-Kütahya", "Hasan Polatkan\t-Eskişehir", "Kocaeli Cengiz Topel-Kocaeli", "Zonguldak Çaycuma-Zonguldak", "Uşak-Uşak", "Mardin-Mardin", "Batman-Batman", "Erzincan-Erzincan", "Muş Sultan Alparslan-Muş", "Şırnak Şerafettin Elçi-Şırnak", "Kahramanmaraş-Kahramanmaraş", "Ağrı Ahmed-i Hani-Ağrı", "Iğdır Şehit Bülent Aydın-Iğdır", "Adıyaman-Adıyaman\t", "Bingöl-Bingöl\t", "Yüksekova Selahaddin Eyyubi-Hakkari", "Amasya Merzifon-Amasya\t", "Kastamonu-Kastamonu\t", "Siirt-Siirt", "Tokat-Tokat\t", "Aydın Çıldır-Aydın", "Balıkesir Merkez-Balıkesir", "Çanakkale Gökçeada-Çanakkale" }));
        NereyeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NereyeCBActionPerformed(evt);
            }
        });

        SaatCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00" }));

        DkCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "30", "45" }));
        DkCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DkCBActionPerformed(evt);
            }
        });

        jLabel13.setText(":");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nereden)
                            .addComponent(Nereye, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Saat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NereyeCB, 0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(SaatCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DkCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NeredenCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(UçuşBilgileri))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UçuşBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nereden)
                    .addComponent(NeredenCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nereye)
                    .addComponent(NereyeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tarih)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Saat)
                    .addComponent(SaatCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DkCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Onayla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ErkekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErkekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErkekActionPerformed

    private void NereyeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NereyeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NereyeCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
        
        
        
        jTextArea1.setText("ROTA: "+NeredenCB.getSelectedItem().toString()+"=>"+NereyeCB.getSelectedItem().toString()+"\nTarih: "+jDateChooser1.getDateFormatString()+"\nSaat: "+SaatCB.getSelectedItem().toString()+":"+DkCB.getSelectedItem().toString());
        
        String s4=HesKoduText.getText();
        String deger4 = s4+"\n"+jTextArea1.getText();
        jTextArea1.setText("Hes Kodu: "+deger4);
        
        String s3=TelText.getText();
        String deger3 = s3+"\n"+jTextArea1.getText();
        jTextArea1.setText("Tel: "+deger3);
        
        String s2=TcText.getText();
        String deger2 = s2+"\n"+jTextArea1.getText();
        jTextArea1.setText("Tc: "+deger2);
        
        String s1=AdSoyadText.getText();
        String deger1 = s1+"\n"+jTextArea1.getText();
        jTextArea1.setText("Biletiniz onaylandı... \n \nBİLET BİLGİLERİ \n ~~~~Yolcu Bilgileri~~~~ \nAd Soyad: "+deger1);
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HesKoduTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HesKoduTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HesKoduTextActionPerformed

    private void TcTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TcTextKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TcTextKeyTyped

    private void TcTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TcTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TcTextActionPerformed

    private void TcTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TcTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TcTextMouseClicked

    private void AdSoyadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdSoyadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdSoyadTextActionPerformed

    private void DkCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DkCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DkCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdSoyadText;
    private javax.swing.JLabel AdıSoyadı;
    private javax.swing.JLabel Cinsiyet;
    private javax.swing.JComboBox<String> DkCB;
    private javax.swing.JRadioButton Erkek;
    private javax.swing.JLabel HesKodu;
    private javax.swing.JTextField HesKoduText;
    private javax.swing.JRadioButton Kadın;
    private javax.swing.JLabel Nereden;
    private javax.swing.JComboBox<String> NeredenCB;
    private javax.swing.JLabel Nereye;
    private javax.swing.JComboBox<String> NereyeCB;
    private javax.swing.JLabel Resim;
    private javax.swing.JLabel Saat;
    private javax.swing.JComboBox<String> SaatCB;
    private javax.swing.JLabel Tarih;
    private javax.swing.JLabel Tc;
    private javax.swing.JTextField TcText;
    private javax.swing.JLabel Tel;
    private javax.swing.JTextField TelText;
    private javax.swing.JLabel UçuşBilgileri;
    private javax.swing.JLabel YbsHavaYolları;
    private javax.swing.JLabel YolcuBilgileri;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
